numpy assignments

assignment 1

In [25]:
import numpy as np
arr=np.random.rand(3,6)
print(arr)


[[0.64478055 0.55027174 0.17054682 0.77398398 0.26633248 0.20767096]
 [0.41387405 0.02390491 0.70460655 0.28752229 0.64243015 0.56793091]
 [0.04381128 0.23282142 0.63735234 0.02640874 0.58585017 0.63772748]]


In [26]:
arr1=arr+[0, 0, 2, 4, 5, 3]
print(arr1)

[[0.64478055 0.55027174 2.17054682 4.77398398 5.26633248 3.20767096]
 [0.41387405 0.02390491 2.70460655 4.28752229 5.64243015 3.56793091]
 [0.04381128 0.23282142 2.63735234 4.02640874 5.58585017 3.63772748]]


In [27]:
arr2=arr1.reshape(9,2)
print(arr2)

[[0.64478055 0.55027174]
 [2.17054682 4.77398398]
 [5.26633248 3.20767096]
 [0.41387405 0.02390491]
 [2.70460655 4.28752229]
 [5.64243015 3.56793091]
 [0.04381128 0.23282142]
 [2.63735234 4.02640874]
 [5.58585017 3.63772748]]


In [28]:
arr3=arr2.T
print(arr3)

[[0.64478055 2.17054682 5.26633248 0.41387405 2.70460655 5.64243015
  0.04381128 2.63735234 5.58585017]
 [0.55027174 4.77398398 3.20767096 0.02390491 4.28752229 3.56793091
  0.23282142 4.02640874 3.63772748]]


In [29]:
mean=np.mean(arr3)
for i in range (2) :
    for j in range (9):
     if arr3[i,j]>mean:
        print ([i,j])



[0, 2]
[0, 5]
[0, 8]
[1, 1]
[1, 2]
[1, 4]
[1, 5]
[1, 7]
[1, 8]


assignment 2


In [30]:
arrrand=np.random.poisson(lam=10,size=20)
print(arrrand)

[12  7  7  4  8 11  6  6 12  4  8  6 10  7 15  6 11 11 12 13]


In [31]:
mean1=np.mean(arrrand)
print(mean1)

8.8


In [32]:
arrrand1=arrrand-mean1
print(arrrand1)

[ 3.2 -1.8 -1.8 -4.8 -0.8  2.2 -2.8 -2.8  3.2 -4.8 -0.8 -2.8  1.2 -1.8
  6.2 -2.8  2.2  2.2  3.2  4.2]


In [33]:
std=np.std(arrrand1)
arrand2=arrrand1/std
print(arrand2)

[ 1.03495396 -0.5821616  -0.5821616  -1.55243095 -0.25873849  0.71153085
 -0.90558472 -0.90558472  1.03495396 -1.55243095 -0.25873849 -0.90558472
  0.38810774 -0.5821616   2.0052233  -0.90558472  0.71153085  0.71153085
  1.03495396  1.35837708]
